### ISSUE TITLE
WorldAPI and WorldManager are names that users may actually already invent and use.

### ISSUE THREAD

**Issue by petersvp** [adamgoodrich/WorldManager#1]
Upon importing this asset, i was surprised that my WorldAPI.WorldManager broke beyond repair. 

Surprise: My marching cubes World Manager was put in namespace WorldAPI. Perfect and EXACT clash!

I immediately renamed your namespace/class to WeatherAPI.WeatherManager and had to fix a lot.

Suggestion: Rename to WeatherManager and put it into something Weather related, not World.

**Comment by adamgoodrich** [comment]
Thanks Peter... yeah unfortunately it is well named and i can see how it might clash :/
Its actually more than a weather manager, hence the way it is named.
Will have a think about alternatives that might make more sense

**Comment by adamgoodrich** [comment]
Ok, just re-namespaced it to WAPI. Hopefully that should resolve your issues.
